### ISSUE TITLE
Attribution required

### ISSUE THREAD

**Issue by rheone** [OliverRC/Postman-WebApi-HelpDocumentation#1]
Much of the source code in this project is based on my [question](http://stackoverflow.com/q/23158379/1090923)/[answer](http://stackoverflow.com/a/23158380/1090923) from [Stackoverflow](http://stackoverflow.com/). Please provide the appropriate attribution as per [Stackoverflow attribution requirements](http://blog.stackoverflow.com/2009/06/attribution-required/)

**Comment by OliverRC** [comment]
You are correct this code was based on your original answer, which I did credit to you in the Readme.
I will adjust the readme further based on the guidelines of attribution link you have included.
